name = "discord-bot-sharkie"
compatibility_date = "2025-10-03"
main = "src/index.ts"

[triggers]
crons = ["0 21 * * *", "0 22 * * *"]

[observability.logs]
enabled = true
invocation_logs = true

[vars]
DISCORD_GUILD_ID="1421162339989717083"
DISCORD_CHANNEL_ID="1421162346436366398"
DISCORD_APP_ID="1422090891513827359"